language:
  ruby

rvm:
  - '1.9'
  - '2.0'
  - '2.1'
  - '2.2'
  - ruby-head
  - rbx

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx

  fast_finish:
    true

script:
  rake test

install:
  - gem install nuggets power_assert
  - gem install --prerelease --development ruby-filemagic

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libmagic-dev
